name: 'biblioteca'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "ALTER SESSION SET TIMEZONE = 'Europe/Madrid'"

models:
  biblioteca:
    example:
      +materialized: table

    staging:
      +materialized: view
      +database: BIBLIOTECA_DEV_SILVER_DB
      raw_biblioteca:
        +schema: STAGING                         

    marts:
      +materialized: incremental
      +database: BIBLIOTECA_DEV_GOLD_DB
      core:
        +schema: CORE
        dimensiones:
          +schema: DIMENSIONES
          +tags: ["dimension"]                       
        hechos:
          +schema: HECHOS
          +tags: ["hechos"]

seeds:
  biblioteca:
    +database: BIBLIOTECA_DEV_BRONZE_DB
    +schema: BRONZE
    tipos_sancion:
      +column_types:
        codigo_tipo: varchar(20)
        descripcion: varchar(200)
        dias_bloqueo: number(3,0)

snapshots:
  biblioteca:
    +database: BIBLIOTECA_DEV_SILVER_DB
    +schema: SNAPSHOTS